---
# https://www.home-assistant.io/integrations/logger/
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: warning
  filters:
    TransportNSW.transportnsw:
      - "No stop events for this query"
    custom_components.ical:
      - "Exception can't compare datetime.datetime to datetime.date in starts/ends"
    custom_components.monitor_docker.helpers:
      - "Can not determine network usage for container ('networks')"
      - "No 'networks' found in raw packet"
      - "Too many errors on 'networks' stats, disabling monitoring"
    custom_components.spook:
      - "Unexpected exception from"
    custom_components.unifi_status.switch:
      - "Failed to scan aps"
    custom_components.unifics.sensor:
      - "Unexpected error fetching sensor data"
    custom_components.unifigateway.sensor:
      - "Failed to access health info"
    custom_components.waternsw.sensor:
      - "Cannot retrieve date, check config"
    homeassistant:
      - "Error doing job: Task exception was never retrieved"
    homeassistant.components.media_player:
      - "Updating spotify media_player took longer than the scheduled update interval 0:00:30"
    homeassistant.components.recorder:
      - "Unhandled database error while processing task EventTask"
    homeassistant.components.template.template_entity:
      - "Template loop detected while processing event"
    homeassistant.components.waze_travel_time.sensor:
      - "Error on retrieving data: empty response"
    homeassistant.helpers.entity:
      - "Expected positive event duration"
      - "Update of media_player.spotify_thomas_baxter is taking over 10 seconds"
    homeassistant.helpers.script.trigger_update_coordinator:
      - "Trigger Update Coordinator: Executing step call service"
      - "Trigger Update Coordinator: Executing step setting variables"
      - "Trigger Update Coordinator: Running script requires passing in a context"
      - "Trigger Update Coordinator: Running template script"
      - "Trigger Update Coordinator: Sequence to get the .* forecast data: Run through weather entities to check if the right forecast is provided: Error executing script. Error for call_service at pos 1: Weather entity '.*' does not support '.*' forecast"
      - "Trigger Update Coordinator: Sequence to get the .* forecast data: Run through weather entities to check if the right forecast is provided: Error executing script. Error for call_service at pos 1: Service call requested response data but did not match any entities"
      - "Trigger Update Coordinator: Sequence to get the .* forecast data: Run through weather entities to check if the right forecast is provided: Error executing script. Error for call_service at pos 1: Entity .* does not support this service."
    homeassistant.loader:
      - "We found a custom integration"
    py.warnings:
      - "InsecureRequestWarning: Unverified HTTPS request is being made to host"
    spotipy.client:
      - "Max Retries reached"
    icloud3:
      - "unsupported operand type(s) for *: 'NoneType' and 'int'"
    snitun.client.client_peer:
      - "0 bytes read on a total of 32 expected bytes"
    hass_nabucasa.remote:
      - "Connection problem to snitun server"

  logs:
    aioharmony.harmonyclient: fatal
    # custom_components.aio_geojson_query: debug
    custom_components.monitor_docker: fatal
    custom_components.monitor_docker.helpers: fatal
    homeassistant: fatal
    homeassistant.config: debug
    # homeassistant.core: info
    homeassistant.helpers.entity: error
    # homeassistant.helpers.script: debug
    # homeassistant.loader: debug
    pychromecast.socket_client: fatal
    slixmpp.basexmpp: error
    slixmpp.stringprep: fatal
